project_id = "wukxgvknolbqvtqsitmd"

[functions.lighthouse-audit]
verify_jwt = false

[functions.notify-admin-signup]
verify_jwt = false

[functions.audit-log]
verify_jwt = false

[functions.manage-user-role]
verify_jwt = false

[functions.setup-2fa]
verify_jwt = false

[functions.verify-2fa-login]
verify_jwt = false

[functions.check-ip-whitelist]
verify_jwt = false

[functions.manage-session]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false