project_id = "pydbejawnenjqgnyyonf"

[functions.keep-alive]
verify_jwt = false

[functions.get-visitor-info]
verify_jwt = false

[functions.track-page-exit]
verify_jwt = false

[functions.sync-leads-to-sheets]
verify_jwt = false

[functions.enrich-visitor]
verify_jwt = false
